# Generated by Django 2.2 on 2019-06-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_emailaddress',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_username',
            new_name='username',
        ),
    ]
