# Generated by Django 2.2 on 2019-06-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='university',
        ),
        migrations.AddField(
            model_name='book',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Universty'),
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'کارشناسی'), ('m', 'کارشناسی ارشد'), ('d', 'دکتری'), ('a', 'غیر دانشگاهی/آزاد')], default='b', help_text='مقطع مربوطه ی کتاب یا جزوه را انتخاب کنید ', max_length=1),
        ),
    ]
