# Generated by Django 2.2 on 2019-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190621_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status2',
            field=models.CharField(blank=True, choices=[('o', 'عمومی'), ('e', 'اختصاصی'), ('p', 'پایه')], default='o', help_text='نوع', max_length=1),
        ),
    ]
