# Generated by Django 2.2 on 2019-07-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='در مورد جزوه و یا کتاب خود بنویسید .', max_length=200),
        ),
    ]
