# Generated by Django 2.2 on 2019-07-04 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
        migrations.RenameField(
            model_name='user2',
            old_name='username',
            new_name='username2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
