# Generated by Django 2.2 on 2019-07-05 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190704_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 5, 17, 20, 1, 474489)),
        ),
    ]
