# Generated by Django 2.2 on 2019-07-05 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_book_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 5, 17, 41, 29, 73845)),
        ),
    ]
