# Generated by Django 2.2 on 2019-07-05 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190705_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 5, 21, 27, 35, 310649)),
        ),
    ]
