# Generated by Django 2.2 on 2019-07-05 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190705_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 6, 0, 2, 29, 387880)),
        ),
    ]
