# Generated by Django 2.2 on 2019-07-06 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190706_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 6, 10, 39, 15, 278120)),
        ),
    ]
