# Generated by Django 2.2 on 2019-07-06 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190706_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 6, 10, 48, 0, 773277)),
        ),
    ]
