# Generated by Django 2.2 on 2019-07-06 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190706_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 6, 10, 54, 41, 546177)),
        ),
    ]
